# Import database utilities for connection handling
from db import init_db, get_connection


def save_incidents(incidents):
    """
    Save correlated incidents into the database.

    Purpose:
    - Persist incident and alert data into the alerts table
    - Enable querying, reporting, and historical analysis
    """

    # Step 1: Establish a connection to the SQLite database
    conn = get_connection()

    # Step 2: Create a cursor object to execute SQL commands
    cursor = conn.cursor()

    # Step 3: Iterate over each incident generated by the correlator
    for incident in incidents:

        # Step 4: Each incident may contain one or more alerts
        # Example: brute force + anomaly detection on same IP
        for alert in incident.get("alerts", []):

            # Step 5: Insert alert data into the database
            # Using parameterized queries to prevent SQL injection
            cursor.execute("""
                INSERT INTO alerts (ip, alert_type, severity, score)
                VALUES (?, ?, ?, ?)
            """, (
                incident.get("ip"),                # IP address of the incident
                alert.get("type"),                # Type of alert (e.g., Brute Force Attack)
                incident.get("severity"),         # Severity level (LOW / MEDIUM / HIGH)
                incident.get("risk_score")        # Computed risk score
            ))

    # Step 6: Commit the transaction to permanently save all inserts
    conn.commit()

    # Step 7: Close the database connection to release resources
    conn.close()